"""create borrow_record table

Revision ID: 497350346c94
Revises: c0b1e33928d4
Create Date: 2026-02-08 19:01:37.989993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497350346c94'
down_revision: Union[str, Sequence[str], None] = 'c0b1e33928d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('borrowed_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_records_book_id'), 'borrow_records', ['book_id'], unique=False)
    op.create_index(op.f('ix_borrow_records_id'), 'borrow_records', ['id'], unique=False)
    op.create_index(op.f('ix_borrow_records_member_id'), 'borrow_records', ['member_id'], unique=False)
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_index(op.f('ix_borrow_records_member_id'), table_name='borrow_records')
    op.drop_index(op.f('ix_borrow_records_id'), table_name='borrow_records')
    op.drop_index(op.f('ix_borrow_records_book_id'), table_name='borrow_records')
    op.drop_table('borrow_records')
    # ### end Alembic commands ###
