"""add timestamps to books and members

Revision ID: e56e55fbfa67
Revises: 497350346c94
Create Date: 2026-02-15 19:09:58.410686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56e55fbfa67'
down_revision: Union[str, Sequence[str], None] = '497350346c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('books', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('members', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('members', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'updated_at')
    op.drop_column('members', 'created_at')
    op.drop_column('books', 'updated_at')
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###
